/**
 * Created by xuehongfeng on 14-11-19.
 */
var boe_network_html="<div class=\"boePageLeftArrowFrame\">"+"    <div id=\"networkPageLeftArrowBtn\" class=\"boeLeftArrowBtnNormal\"></div>"+"</div>"+"<div class=\"boe_network_page_ContentFrame\">"+"    <ul id=\"boeNetworkGridUl\" class style=\"width: 1270px;height:510px;overflow: hidden\">"+"        <li class=\"boe_network_GridUlLi_2_Normal\">"+"            <div id = \"net_select\">"+"            <img id =\"netlogo\" class = \"img_netlogo_normal\">"+"            <img id =\"netlogo_hilight\" class = \"img_netlogo_hilight\" >"+"            <span id = \"nettype\" style=\"position:absolute;left:180px;width:350px\"></span>"+"            <img id =\"arrow\" class = \"img_arrow_normal\">"+"            <img id =\"arrow_focus\" class = \"img_arrow_focus\">"+"            </div>"+"        </li>"+"    </ul>"+"</div>"+"<div class=\"boePageRightArrowFrame\">"+"    <div id=\"networkPageRightArrowBtn\" class=\"boeRightArrowBtnNormal\"></div>"+"</div>";

var boe_netbg_html="<div id=\"navNetworkBGLeftArrow\" class=\"navNetworkBGLeftArrowNormal\">"+"</div>"+"<div class=\"boe_netbg_page_ContentFrame\">"+"    <ul id=\"boeNetbgGridUl\">"+"        <li class=\"boe_netbg_GridUlLi_2_Normal\">"+"            <div id = \"netbg_select\">"+"                <img id =\"netbglogo\" class = \"img_netbglogo_normal\">"+"                <img id =\"netbglogo_disable\" class = \"img_netbglogo_disable\" >"+"                <span id = \"netbgtype\" class =\"netbgtype\"></span>"+"                <span id = \"netbgtype_marquee\" class =\"netbgtype_marquee\"></span>"+"                <img id =\"netbg_arrow\" class = \"img_netbg_arrow_normal\">"+"                <img id =\"netbg_arrow_disable\" class = \"img_netbg_arrow_disable\">"+"            </div>"+"        </li>"+"    </ul>"+"</div>"+"<div id=\"navNetworkBGRightArrow\" class=\"navNetworkBGRightArrowNormal\">"+"</div>";

var boe_search_wifi_html="<div class=\"boeLoading\">"+"    <img id=\"boeSearWifiDialogImg\" src=\"img/loading.png\" class=\"boeDialogLoadingImg\">"+"    <div id=\"boeSearWifiDialogText\" class=\"boeDialogLoadingText\"></div>"+"</div>";

var boe_NetSetWifiNotPlugin_html = "<div  class=\"boeWifiNotPluginDialog\" >"+"    <div class=\"boeWifiNotPluginFrame\">"+"        <div class=\"WifiNotPluginContent\" style=\"text-align: center;vertical-align:middle;display: table-cell\">"+"            <div id=\"boeNetSetWifiNotPluginInfo\" style=\"color: rgba(255,255,255,0.7);font-size:36px\"></div>"+"        </div>"+"    </div>"+"</div>";

var boe_NetworkWifiSetPage_html ="<div class=\"navNetworkWifiSetPageContent\">"+"    <div id=\"boeNetworkManualAddBtnNormal\" class=\"navNetworkManualAddBtnNormal\">Manual Add Network</div>"+"    <div class=\"navNetworkManualUlContent\">"+"        <div id = \"boeNetworkManualUlUpArrow\" class=\"navNetworkManualUlUpArrow\">"+"            <img src=\"img/network/upArrow.png\">"+"        </div>"+"        <div id=\"boeNetSetWifiSetListFrame\" style=\"height: 500px;overflow: hidden\">"+"        <ul id=\"boeNetworkWifiAutoResultUl\" class=\"navNetworkWifiAutoResultUl\" style=\"float: left;position: relative;top: 0px;\">"+"            <li class=\"navNetworkWifiAutoResultLiNormal\">"+"                <span id=\"boeNetworkWifiName\" class=\"navNetworkWifiName\"></span>"+"                <span id=\"boeNetworkWifiConnState\" class=\"navNetworkWifiConnState\"></span>"+"                <span id=\"boeNetworkWifiSecType\" class=\"navNetworkSecType\"></span>"+"                <span class=\"boeWifiRight2\"><img id=\"boeNetworkWifiStateImg\" alt=\"\" style=\"border: 0px;display: inline-block\"></span>"+"                <span class=\"boeWifiRight\"><img id=\"boeNetworkWifiSecImg\" alt=\"\" style=\"border: 0px;display: inline-block\"></span>"+""+"            </li>"+"        </ul>"+""+"        </div>"+"        <div id=\"boeWifiAutoListScrollCon\" class = \"boeAutoScroll\">"+"            <div id=\"boeWifiAutoListScrollBar\" style=\"width: 4px;position:relative;background-color:#555b60;border-radius: 4px;\"></div>"+"        </div>"+"        <div id = \"boeNetworkManualUlDownArrow\" class=\"navNetworkManualUlDownArrow\">"+"            <img src=\"img/network/downArrow.png\">"+"        </div>"+""+"    </div>"+"</div>";

var boe_NetworkWifiPWInputDialog_html = "<div id=\"networkWifiPWInputContent\" class=\"networkWifiPWInputContent\">"+"    <div class=\"navDialogHead\">"+"        <div id=\"boeWifiAutoConnPWTitle\" class=\"navDialogTitle\"></div>"+"    </div>"+"    <div class=\"navDialogContentFrame_240\" style=\"\">"+"        <div id=\"boeNetSetInputDisplay0\" class=\"navInputLine\" style=\"padding-top: 40px\">"+"            <div id=\"boeWifiAutoPWInputText0\" class=\"navInputTitle\">password:</div>"+"            <input id=\"boeWifiAutoPWInput0\" class=\"navInputContentFocus\">"+"        </div>"+"        <div id=\"boeNetSetInputDisplay1\" class=\"navInputLine\" style=\"padding-top: 40px\">"+"            <div id=\"boeWifiAutoPWInputText1\" class=\"navInputTitle\">password:</div>"+"            <input id=\"boeWifiAutoPWInput1\" class=\"navInputContentFocus\">"+"        </div>"+"        <div class=\"navInputLine\" style=\"padding-top: 40px\">"+"            <img id=\"boeNetSetPWCheckBox\" class=\"navCheckBoxImg\">"+"            <span id=\"boeNetSetPWCheckInfo\" class=\"navSetItemTitle\"></span>"+"        </div>"+"    </div>"+"    <div class=\"navDialogFootFrame\">"+"        <span id=\"boeWifiAutoConnBtn\" class=\"navDialogFootLeftNormal\">OK</span>"+"        <span id=\"boeWifiAutoCancelBtn\" class=\"navDialogFootRightNormal\">Cancel</span>"+"    </div>"+"</div>";

var  boe_NetworkWifiAddDialog_html = "<div  class=\"networkWifiAddDialogContent\">"+"    <div class=\"boeWifiAddDialogHead\">"+"        <div id=\"boeNetSetWifiAddHeadTitle\" class=\"boeWifiAddDialogTitle\"></div>"+"    </div>"+"    <div class=\"boeWifiAddDialogContentFrame\" style=\"\">"+"        <div class=\"boeWifiAddInputLine\" style=\"padding-top: 30px\">"+"            <div id=\"boeNetSetSSIDInputTitle\" class=\"boeWifiAddInputTitle\">SSID:</div>"+"            <input id=\"boeNetSetSSIDInput\" class=\"boeWifiAddInputContentFocus\">"+"        </div>"+"        <div class=\"boeWifiAddInputLine\" style=\"padding-top: 30px\">"+"            <div id=\"boeNetSetSecSelectTitle\" class=\"boeWifiAddInputTitle\"></div>"+"            <div id=\"boeNetSetSecSelectFrame\" class=\"boeWifiAddSelectFrameNormal\">"+"                <div id=\"boeNetSetSecSelectType\" class=\"boeWifiAddSelectText\">none</div>"+"                <div id=\"boeNetSetSecSelectImg\" class=\"boeWifiAddSelectRightImg\"></div>"+"            </div>"+"        </div>"+"        <div id=\"boeNetSetSecSelectListFrame\" class=\"boeWifiAddSelectListFrameNormal\">"+"            <ul id=\"boeNetSetSecSelectList\" class=\"boeWifiAddSelectListContent\">"+"                <li class=\"boeWifiAddSelectLiFocus\">"+"                    <div id=\"boeNetSetSecTypeItem\" class=\"boeWifiAddSelectItem\">aaaaaaaaaaaaaaaaaaaaaaaa</div>"+"                </li>"+"            </ul>"+"        </div>"+""+"    </div>"+"    <div class=\"navDialogFootFrame\">"+"        <div id=\"boeNetSetWifiAddConnBtn\" class=\"navDialogFootLeftNormal\">OK</div>"+"        <div id=\"boeNetSetWifiAddCancelBtn\" class=\"navDialogFootRightNormal\">Cancel</div>"+"    </div>"+"</div>";

var boe_NetworkConnNetDialog_html = "<div class=\"boeLoading\">"+"    <img id=\"boeNetworkLoadingDialogImg\" src=\"img/loading.png\" class=\"boeDialogLoadingImg\">"+"    <div id=\"boeNetworkLoadingDialogText\" class=\"boeDialogLoadingText\"></div>"+"</div>";

var boe_NetworkConnResDialog_html = "<div class=\"boeLoading\">"+"    <img id=\"boeNetworkConnNetResultImg\" src=\"img/network/success.png\" class=\"boeDialogLoadingImg\">"+"    <div id=\"boeNetworkConnNetResultTip\" class=\"boeDialogLoadingText\"></div>"+"</div>";

var boe_NetworkEthernetType_html ="<div class=\"navNetworkEthernetSetPageContent\">"+"    <ul id=\"navNetworkEthernetTypeUl\" class=\"navNetworkEthernetTypeUl\" >"+"        <li class=\"navNetworkEthernetTypeLiNormal\">"+"            <img id=\"navNetworkEthernetTypeImg\" class=\"navNetworkEthernetTypeImgNormal\">"+"            <div id=\"navNetworkEthernetTypeTitle\" class=\"navNetworkEthernetTypeTitleNormal\"></div>"+"        </li>"+"    </ul>"+"</div>";

var boe_NetworkEthernetSetPage_html = "<div class=\"navNetworkEthernetSetPageContent\">"+"    <ul id=\"navNetworkEtherIPV4InfoUl\" class=\"navNetworkEtherIPV4InfoUlClass\">"+"        <li class=\"navNetworkEtherIPV4InfoLi\">"+"            <span id=\"navNetworkEtherIPV4Title\" class=\"navNetworkEtherIPV4TitleNormal\" ></span>"+"            <input id=\"navNetworkEtherIPV4Input0\" class=\"navNetworkIpAddrInputNormal\"/>"+"            <input id=\"navNetworkEtherIPV4Input1\" class=\"navNetworkIpAddrInputNormal\"/>"+"            <input id=\"navNetworkEtherIPV4Input2\" class=\"navNetworkIpAddrInputNormal\"/>"+"            <input id=\"navNetworkEtherIPV4Input3\" class=\"navNetworkIpAddrInputNormal\"/>"+"        </li>"+"    </ul>"+"    <div class=\"navNetworkBtnRow\">"+"        <div id=\"navNetworkEtherIPCancelBtn\" class=\"navNetworkBtnNormal\">Cancel</div>"+"        <div id=\"navNetworkEtherIPSaveBtn\" class=\"navNetworkBtnNormal\">Save</div>"+"    </div>"+"</div>";
